/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as IaWhatsappRouteImport } from './routes/ia-whatsapp'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConectarTokenRouteImport } from './routes/conectar.$token'

const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const IaWhatsappRoute = IaWhatsappRouteImport.update({
  id: '/ia-whatsapp',
  path: '/ia-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConectarTokenRoute = ConectarTokenRouteImport.update({
  id: '/conectar/$token',
  path: '/conectar/$token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/financeiro': typeof FinanceiroRoute
  '/ia-whatsapp': typeof IaWhatsappRoute
  '/portal': typeof PortalRoute
  '/conectar/$token': typeof ConectarTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/financeiro': typeof FinanceiroRoute
  '/ia-whatsapp': typeof IaWhatsappRoute
  '/portal': typeof PortalRoute
  '/conectar/$token': typeof ConectarTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clientes': typeof ClientesRoute
  '/financeiro': typeof FinanceiroRoute
  '/ia-whatsapp': typeof IaWhatsappRoute
  '/portal': typeof PortalRoute
  '/conectar/$token': typeof ConectarTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clientes'
    | '/financeiro'
    | '/ia-whatsapp'
    | '/portal'
    | '/conectar/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clientes'
    | '/financeiro'
    | '/ia-whatsapp'
    | '/portal'
    | '/conectar/$token'
  id:
    | '__root__'
    | '/'
    | '/clientes'
    | '/financeiro'
    | '/ia-whatsapp'
    | '/portal'
    | '/conectar/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientesRoute: typeof ClientesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  IaWhatsappRoute: typeof IaWhatsappRoute
  PortalRoute: typeof PortalRoute
  ConectarTokenRoute: typeof ConectarTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-whatsapp': {
      id: '/ia-whatsapp'
      path: '/ia-whatsapp'
      fullPath: '/ia-whatsapp'
      preLoaderRoute: typeof IaWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conectar/$token': {
      id: '/conectar/$token'
      path: '/conectar/$token'
      fullPath: '/conectar/$token'
      preLoaderRoute: typeof ConectarTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientesRoute: ClientesRoute,
  FinanceiroRoute: FinanceiroRoute,
  IaWhatsappRoute: IaWhatsappRoute,
  PortalRoute: PortalRoute,
  ConectarTokenRoute: ConectarTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
